# Resumen

## Notas importantes 2º EDA: 

- Las columnas de `age` y `attrition` no aparecen en el csv.
- Porcentaje de valores nulos elevados en las columnas: `department`, `educationfield`, `hourlyrate`, `overtime`. 

## Aún por hacer:

- Volver a introducir columnas `age` y `attrition`.
- Transformar datos en columna `age`.
- `distancefromhome`, valores aún en negativo.
- `monthlyincome`, `monthlyrate`, `performancerating`, `totalworkingyears`, `worklifebalance`, `salary` ahora solo dan valores nulos.
- `overtime` deberia ser fillna a 'no' o 'unknown'?
- Limpiar/sacar informacion de `roledepartment` porque está destinada a eliminación.
- `remotework` datos aun sin unificar.


## Memoria aún por actualizar: 

- `employeecount` solo se especifica que se ha eliminado en el índice.
- `employeenumber` solo se especifica que se ha actualizado en el índice.
- `maritalstatus`: no se especifica que se han actualizado los valores nulos a 'unknown'. 
- `over18`, `yearsincurrentrole`, `sameasmonthlyincome`, `numberchildren`: no se especifica que la columna ha sido eliminada.
- Otras columnas a revisar en la memoria: `envirenmentsatisfaction`, `gender`, `hourlyrate`, `jobinvolvement`, `joblevel`, `jobsatisfaction`, `relationshipsatisfaction`, `standardhours`, `numcompaniesworked`.




In [2]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# ------------------------------------------------------------------------------
from scipy.stats import shapiro, kstest

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv('raw_data_limpio_2.csv', index_col=0)

df.head(5)

businesstravel  dailyrate              department  distancefromhome  \
attrition                                                                       
no            non-travel    2015.72                     NaN                 6   
no            non-travel    2063.39                     NaN                 1   
no         travel_rarely    1984.25  research & development                 4   
no         travel_rarely    1771.40                     NaN                 2   
no            non-travel    1582.77                     NaN                 3   

           education    educationfield  employeenumber  \
attrition                                                
no                 3               NaN               1   
no                 4     life sciences               2   
no                 2  technical degree               3   
no                 4           medical               4   
no                 3  technical degree               5   

           environmentsatisfaction gender  hourlyrate  jobinvolvement  \
attrition                                                               
no                               1      m         NaN               3   
no                               3      m         NaN               2   
no                               3      m         NaN               3   
no                               1      f         NaN               3   
no                               1      f         NaN               4   

           joblevel            jobrole  jobsatisfaction maritalstatus  \
attrition                                                               
no                5  research director                3       unknown   
no                5            manager                3       unknown   
no                5            manager                4       married   
no                4  research director                3       married   
no                4    sales executive                1      divorced   

           monthlyincome  monthlyrate  numcompaniesworked overtime  \
attrition                                                            
no                   NaN          NaN                   7       no   
no                   NaN          NaN                   0      NaN   
no                   NaN          NaN                   1       no   
no                   NaN          NaN                   3      NaN   
no                   NaN          NaN                   2       no   

           percentsalaryhike  performancerating  relationshipsatisfaction  \
attrition                                                                   
no                        13                NaN                         3   
no                        14                NaN                         1   
no                        11                NaN                         4   
no                        19                NaN                         2   
no                        12                NaN                         4   

          standardhours  stockoptionlevel  totalworkingyears  \
attrition                                                      
no            full time                 0                NaN   
no            full time                 1                NaN   
no            full time                 0                NaN   
no            full time                 2                NaN   
no            full time                 1                NaN   

           trainingtimeslastyear  worklifebalance  yearsatcompany  \
attrition                                                           
no                             5              NaN              20   
no                             5              NaN              33   
no                             3              NaN              22   
no                             2              NaN              20   
no                             5              NaN              19   

           yearssincelastpromotion  yearswithcu

In [ ]:
#confirmando columna: 'employeecount', 'sameasmonthlyincome', 'numberchildren', 'over18', 'yearsincurrentrole' han sido eliminadas: 

df.columns


# Importante: columnas de 'age' y 'attrition' no aparecen en el csv!!!

# NOTAS: en la memoria, la columna de 'Roledepartment' aparece con el simbolo de eliminar pero aun sigue en el csv. 

Index(['businesstravel', 'dailyrate', 'department', 'distancefromhome',
       'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'standardhours', 'stockoptionlevel', 'totalworkingyears',
       'trainingtimeslastyear', 'worklifebalance', 'yearsatcompany',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'salary', 'roledepartament', 'remotework'],
      dtype='object')

- Comprobación columna 'age': 

In [ ]:
# Importante: columnas de 'age' y 'attrition' no aparecen en el csv!!!
# datos aún tendrían que ser transformados 
df['age'].unique()

KeyError: 'age'

- Comprobación columna 'attrition': 

In [ ]:
# Importante: columnas de 'age' y 'attrition' no aparecen en el csv!!!

df['attrition'].unique()

KeyError: 'attrition'

- Comprobación columna 'businesstravel': 

In [ ]:
# todo correcto; memoria estaba actualizada

df['businesstravel'].unique()

array(['non-travel', 'travel_rarely', 'travel_frequently'], dtype=object)

- Comprobación columna 'dailyrate': 

In [ ]:
# todo correcto; memoria estaba actualizada

df['dailyrate'].unique()

array([2015.72, 2063.39, 1984.25, 1771.4 , 1582.77, 1771.92, 1032.49,
        556.26, 1712.18, 1973.98, 2060.71, 1382.75, 1362.52, 2016.55,
       1861.37, 1985.7 , 1108.92, 1728.38,  639.79, 2047.5 ,  412.8 ,
       1077.87, 1657.4 ,  331.19, 1059.19, 1080.75,  635.76,  487.09,
        290.04,  476.15, 1749.74, 1063.32,  557.76,  608.94, 1119.96,
        610.17,  685.7 , 1441.66, 1374.29,  689.93,  488.53, 1431.24,
       1964.96, 1652.34,  991.82, 1187.54,  444.27, 1758.71,  522.79,
        380.92, 2047.71,  238.13,  592.94, 1075.29,  654.85,  242.25,
        316.95, 1288.65,  827.46, 1760.98,  922.69, 1988.38,  575.4 ,
        277.64,  763.8 ,  910.31,  369.26, 1834.34, 1879.12, 1400.8 ,
       1979.92, 1766.66, 1979.61, 1032.57,  824.16,  730.79,  487.29,
        351.52,  302.2 , 1241.29, 1591.67,  528.87,  992.44,  516.9 ,
       1963.72, 1073.02,  288.17,  585.41, 1980.64,  867.9 ,  345.43,
        547.75,  789.7 , 1321.46,  679.51,  259.9 , 1764.18, 1353.65,
        323.04,  458

- Comprobación columna 'department': 

In [ ]:
# estandarización y espaciado correcto; memoria estaba actualizada

df['department'].unique()

array([nan, 'research & development', 'sales', 'human resources'],
      dtype=object)

In [15]:
df['department'].value_counts()


department
research & development    196
sales                      91
human resources            15
Name: count, dtype: int64

In [ ]:
# numero total de valores nulos: 

df['department'].value_counts(dropna=False)

department
NaN                       1312
research & development     196
sales                       91
human resources             15
Name: count, dtype: int64

In [ ]:
# porcentaje de valores nulos (tal y como sugiere PILI):

round(df['department'].value_counts(dropna=False, normalize=True)*100, 2)

department
NaN                       81.29
research & development    12.14
sales                      5.64
human resources            0.93
Name: proportion, dtype: float64

- Comprobación columna 'distancefromhome': 

In [ ]:
# algunos valores aún siguen en negativo

df['distancefromhome'].unique()

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

- Comprobación columna 'education': 

In [ ]:
# todo correcto; memoria estaba actualizada

df['education'].unique()

array([3, 4, 2, 1, 5])

- Comprobación columna 'educationfield': 

In [ ]:
# estandarización y espaciado correcto; memoria estaba actualizada

df['educationfield'].unique()

array([nan, 'life sciences', 'technical degree', 'medical', 'other',
       'marketing', 'human resources'], dtype=object)

In [27]:
df['educationfield'].value_counts()


educationfield
life sciences       349
medical             276
marketing           104
technical degree     69
other                59
human resources      12
Name: count, dtype: int64

In [29]:
# numero total de valores nulos: 

df['educationfield'].value_counts(dropna=False)

educationfield
NaN                 745
life sciences       349
medical             276
marketing           104
technical degree     69
other                59
human resources      12
Name: count, dtype: int64

In [30]:
# porcentaje de valores nulos (tal y como sugiere PILI):

round(df['educationfield'].value_counts(dropna=False, normalize=True)*100, 2)

educationfield
NaN                 46.16
life sciences       21.62
medical             17.10
marketing            6.44
technical degree     4.28
other                3.66
human resources      0.74
Name: proportion, dtype: float64

- Comprobación columna 'employeecount': 

In [ ]:
# confirmando que ha sido eliminada; la memoria no está actualizada

df['employeecount'].unique()

KeyError: 'employeecount'

- Comprobación columna 'employeenumber': 

In [ ]:
# todo correcto, cero duplicados; memoria sin actualizar

df['employeenumber'].unique()

array([   1,    2,    3, ..., 1612, 1613, 1614], shape=(1614,))

In [33]:
df['employeenumber'].value_counts()

employeenumber
1       1
2       1
3       1
4       1
5       1
       ..
1610    1
1611    1
1612    1
1613    1
1614    1
Name: count, Length: 1614, dtype: int64

In [40]:
len(df)

1614

In [ ]:
df.duplicated(subset="employeenumber").sum()

np.int64(0)

- Comprobación columna 'environmentsatisfaction': 

In [ ]:
# todo parece correcto; memoria sin actualizar 

df['environmentsatisfaction'].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

- Comprobación columna 'gender': 

In [ ]:
# todo correcto; memoria sin actualizar 

df['gender'].unique()

array(['m', 'f'], dtype=object)

- Comprobación columna 'hourlyrate': 

In [ ]:
# redondeo correcto pero aún gran número de valores nulos; memoria sin actualizar

df['hourlyrate'].unique()

array([   nan,  69.53, 172.84, 216.05,  79.97, 129.06, 246.75, 207.17,
        60.89,  36.25, 140.  ,  86.24, 197.85,  61.07, 245.62, 123.98,
       148.44, 255.96, 134.41,  71.93, 113.79, 175.1 , 247.49, 220.83,
        91.35,  37.77, 198.96, 124.05, 247.58, 108.49,  43.18,  68.47,
        32.49,  55.26,  83.47,  79.26,  72.29,  45.96,  31.66,  65.19,
        52.25, 143.92, 113.4 , 143.19, 139.87,  70.57,  97.05,  45.02,
       223.48, 134.98,  74.4 ,  67.14,  58.06,  35.05,  73.19, 164.33,
        43.54,  54.8 , 252.6 ,  83.82,  46.71,  33.  ,  70.78,  69.23,
        54.55,  81.53, 217.76,  50.76,  88.24,  57.37, 115.27,  35.78,
        59.96,  28.21,  54.91, 227.49,  78.18,  54.09, 177.02,  52.97,
        46.39,  80.89, 118.7 ,  56.4 ,  31.34,  38.36,  35.67,  84.  ,
        55.25,  28.71,  69.29,  69.77,  50.87,  38.17, 244.36,  83.38,
        25.97, 243.03,  26.1 ,  76.61,  33.82,  41.42,  89.39, 240.72,
        82.67,  28.04,  34.27, 141.41,  32.8 ,  68.4 ,  84.32, 153.92,
      

In [46]:
df['hourlyrate'].value_counts()

hourlyrate
36.25     75
69.53     74
129.06    38
197.85    14
246.75     8
          ..
108.23     1
247.48     1
67.42      1
34.82      1
133.16     1
Name: count, Length: 194, dtype: int64

In [47]:
df['hourlyrate'].value_counts(dropna=False)

hourlyrate
NaN       1210
36.25       75
69.53       74
129.06      38
197.85      14
          ... 
108.23       1
247.48       1
67.42        1
34.82        1
133.16       1
Name: count, Length: 195, dtype: int64

In [ ]:
# porcentaje de valores nulos (tal y como sugiere PILI):

round(df['hourlyrate'].value_counts(dropna=False, normalize=True)*100, 2)

hourlyrate
NaN       74.97
36.25      4.65
69.53      4.58
129.06     2.35
197.85     0.87
          ...  
108.23     0.06
247.48     0.06
67.42      0.06
34.82      0.06
133.16     0.06
Name: proportion, Length: 195, dtype: float64

- Comprobación columna 'jobinvolvement': 

In [ ]:
#todo correcto; memoria sin actualizar 

df['jobinvolvement'].unique()

array([3, 2, 4, 1])

- Comprobación columna 'joblevel': 

In [ ]:
#todo correcto; memoria sin actualizar 

df['joblevel'].unique()

array([5, 4, 3, 2, 1])

- Comprobación columna 'jobrole': 

In [ ]:
# estandarización y espaciado correcto; memoria actualizada

df['jobrole'].unique()

array(['research director', 'manager', 'sales executive',
       'manufacturing director', 'research scientist',
       'healthcare representative', 'laboratory technician',
       'sales representative', 'human resources'], dtype=object)

- Comprobación columna 'jobsatisfaction': 

In [53]:
# todo correcto; memoria sin actualizar 

df['jobsatisfaction'].unique()

array([3, 4, 1, 2])

- Comprobación columna 'maritalstatus': 

In [ ]:
# Nulos sustituidos por 'unknown', estandarización y espaciado correcto; memoria sin actualizar (no se especifica que se han actualizado los valores nulos)

df['maritalstatus'].unique()

array(['unknown', 'married', 'divorced', 'single'], dtype=object)

In [55]:
df['maritalstatus'].value_counts(dropna=False)

maritalstatus
unknown     651
married     439
single      325
divorced    199
Name: count, dtype: int64

- Comprobación columna 'monthlyincome': 

In [ ]:
# ahora solo da valores nulos! 

df['monthlyincome'].unique()

array([nan])

In [58]:
df['monthlyincome'].value_counts(dropna=False)

monthlyincome
NaN    1614
Name: count, dtype: int64

In [67]:
# porcentaje de valores nulos (tal y como sugiere PILI):

round(df['monthlyincome'].value_counts(dropna=False, normalize=True)*100, 2)

monthlyincome
NaN    100.0
Name: proportion, dtype: float64

- Comprobación columna 'monthlyrate': 

In [ ]:
# ahora solo da valores nulos! 

df['monthlyrate'].unique()

array([nan])

In [60]:
df['monthlyrate'].value_counts(dropna=False)

monthlyrate
NaN    1614
Name: count, dtype: int64

In [68]:
# porcentaje de valores nulos (tal y como sugiere PILI):

round(df['monthlyrate'].value_counts(dropna=False, normalize=True)*100, 2)

monthlyrate
NaN    100.0
Name: proportion, dtype: float64

- Comprobación columna 'numcompaniesworked': 

In [ ]:
# todo correcto; memoria sin actualizar 

df['numcompaniesworked'].unique()

array([7, 0, 1, 3, 2, 4, 8, 9, 5, 6])

- Comprobación columna 'over18': 

In [ ]:
# confirmando que ha sido eliminada; la memoria no está actualizada

df['over18'].unique()

KeyError: 'over18'

- Comprobación columna 'overtime': 

In [ ]:
# consulta de nulos con PILI?

df['overtime'].unique()

array(['no', nan, 'yes'], dtype=object)

In [64]:
df['overtime'].value_counts()

overtime
no     682
yes    256
Name: count, dtype: int64

In [65]:
df['overtime'].value_counts(dropna=False)

overtime
no     682
NaN    676
yes    256
Name: count, dtype: int64

In [69]:
# porcentaje de valores nulos (tal y como sugiere PILI):

round(df['overtime'].value_counts(dropna=False, normalize=True)*100, 2)

overtime
no     42.26
NaN    41.88
yes    15.86
Name: proportion, dtype: float64

- Comprobación columna 'percentsalaryhike': 

In [ ]:
# todo correcto; memoria actualizada

df['percentsalaryhike'].unique()

array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18])

- Comprobación columna 'performancerating': 

In [ ]:
# solo da valores nulos! 

df['performancerating'].unique()

array([nan])

In [72]:
df['performancerating'].value_counts()

Series([], Name: count, dtype: int64)

In [74]:
df['performancerating'].value_counts(dropna=False)

performancerating
NaN    1614
Name: count, dtype: int64

In [75]:
# porcentaje de valores nulos (tal y como sugiere PILI):

round(df['performancerating'].value_counts(dropna=False, normalize=True)*100, 2)

performancerating
NaN    100.0
Name: proportion, dtype: float64

- Comprobación columna 'relationshipsatisfaction': 

In [77]:
# todo correcto; memoria sin actualizar 

df['relationshipsatisfaction'].unique()

array([3, 1, 4, 2])

- Comprobación columna 'standardhours': 

In [ ]:
# estandarización correcta y valores nulos eliminados; memoria sin actualizar 

df['standardhours'].unique()

array(['full time', 'part time'], dtype=object)

- Comprobación columna 'stockoptionlevel': 

In [ ]:
# todo correcto; memoria actualizada 

df['stockoptionlevel'].unique()

array([0, 1, 2, 3])

- Comprobación columna 'totalworkingyears': 

In [ ]:
# ahora solo aparecen nulos! 

df['totalworkingyears'].unique()

array([nan])

- Comprobación columna 'trainingtimeslastyear': 

In [ ]:
# todo correcto; memoria actualizada

df['trainingtimeslastyear'].unique()

array([5, 3, 2, 0, 1, 4, 6])

- Comprobación columna 'worklifebalance': 

In [ ]:
# ahora solo aparecen nulos! 

df['worklifebalance'].unique()

array([nan])

- Comprobación columna 'yearsatcompany': 

In [ ]:
# todo correcto; memoria actualizada

df['yearsatcompany'].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])

- Comprobación columna 'yearsincurrentrole': 

In [ ]:
# confirmando que ha sido eliminada; la memoria no está actualizada

df['yearsincurrentrole'].unique()

KeyError: 'yearsincurrentrole'

- Comprobación columna 'yearssincelastpromotion': 

In [ ]:
# todo correcto; memoria estaba actualizada

df['yearssincelastpromotion'].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])

- Comprobación columna 'yearswithcurrmanager': 

In [ ]:
# todo correcto; memoria estaba actualizada

df['yearswithcurrmanager'].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16])

- Comprobación columna 'sameasmonthlyincome': 

In [ ]:
# confirmando que ha sido eliminada; la memoria no está actualizada

df['sameasmonthlyincome'].unique()

KeyError: 'sameasmonthlyincome'

- Comprobación columna 'datebirth': 

In [ ]:
# todo correcto; memoria estaba actualizada

df['datebirth'].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005])

- Comprobación columna 'salary': 

In [ ]:
# ahora solo aparecen nulos! 

df['salary'].unique()

array([nan])

- Comprobación columna 'roledepartament': 

In [92]:
# columna destinada a ser eliminada 

df['roledepartament'].unique()

array([nan, ' manager  -  research & development ',
       ' healthcare representative  -  research & development ',
       ' sales executive  -  sales ',
       ' laboratory technician  -  research & development ',
       ' manufacturing director  -  research & development ',
       ' research scientist  -  research & development ',
       ' research director  -  research & development ',
       ' human resources  -  human resources ', ' manager  -  sales ',
       ' sales representative  -  sales ',
       ' manager  -  human resources '], dtype=object)

- Comprobación columna 'numberchildren': 

In [ ]:
# confirmando que ha sido eliminada; la memoria no está actualizada

df['numberchildren'].unique()

KeyError: 'numberchildren'

- Comprobación columna 'remotework': 

In [ ]:
# datos aún sin unificar 

df['remotework'].unique()

array(['yes', '1', 'false', '0', 'true'], dtype=object)